### ISSUE TITLE
Renaming tabs to allow for easy identification

### ISSUE THREAD

**Issue by NixGD** [angelinahli/eagt-practice#6]

**Comment by NixGD** [comment]
Also check if page title changes after donation on real-FB

**Comment by angelinahli** [comment]
Resolved -- the page titles don't change after a donation on real FB. Changed the page titles for each individual page type.

**Comment by NixGD** [comment]
This got broken because `componentDidMount` don't automatically call `super()`.  There are easy quick and dirty solutions but we may want to rethink page inheritance anyway to be more react-y.
