### ISSUE TITLE
Canceling out of modals

### ISSUE THREAD

**Issue by NixGD** [angelinahli/eagt-practice#7]
Especially for "confirm your donation."   Think about keyboard shortcuts (tabbing around between buttons).

**Comment by angelinahli** [comment]
Made confirm your donation button work. For now, we aren't going to modify all the other form details. They are there for visual realism -- users should not be expected to use them, and therefore they shouldn't have the option to.

Also, it's pretty likely that users shouldn't be using keyboard shortcuts to toggle to and click buttons anyway.
